import { Stack, useRouter } from "expo-router";
import React from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAppPalette, AppPalette } from "@/hooks/use-app-palette";
const UPDATED="20 September 2026";
function Section({title,children}:{title:string;children:React.ReactNode}){const palette=useAppPalette();const s=createStyles(palette);return <View style={s.section}><Text style={s.heading}>{title}</Text><Text style={s.body}>{children}</Text></View>}
export default function TermsScreen(){const palette=useAppPalette();const s=createStyles(palette);const router=useRouter();return <><Stack.Screen options={{headerShown:false}}/><SafeAreaView style={s.screen} edges={["top"]}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹ Help & About</Text></Pressable><Text style={s.title}>Terms of Use</Text><Text style={s.meta}>Progressive Bodyweight Hypertrophy Coach (PBH){"\n"}Last updated: {UPDATED}</Text>
<Pressable onPress={() => Linking.openURL("https://roloje777.github.io/pbh-public/terms.html")} style={s.onlineButton} accessibilityRole="link"><Text style={s.onlineButtonText}>View Terms of Use Online ↗</Text></Pressable>
<Section title="1. About these terms">These Terms govern your use of PBH, developed and published by João Rolo. By using PBH, you agree to use the application responsibly and in accordance with applicable law.</Section>
<Section title="2. Fitness guidance, not medical care">PBH provides general exercise, fitness and training guidance. It does not provide medical diagnosis, treatment or emergency services and does not replace advice from a doctor, physiotherapist or other qualified healthcare professional. If you have an injury, medical condition, concerning symptoms or uncertainty about whether exercise is appropriate for you, seek appropriate professional advice.</Section>
<Section title="3. Exercise responsibility">Exercise involves inherent risks. Use controlled technique, an appropriate training environment and equipment that is safe and suitable for the exercise. Stop if you experience pain, dizziness, chest pain, unusual shortness of breath or other concerning symptoms. PBH recommendations, targets, recovery suggestions and progression decisions are guidance and do not override your judgement or professional advice.</Section>
<Section title="4. Adaptive coaching">Match or Beat targets, recovery guidance, deloads, verification workouts, adaptive rest, adaptive volume and other coaching features are generated from program rules and information available to PBH. They are training aids rather than guarantees of performance, muscle growth, safety or results.</Section>
<Section title="5. Your training data">You are responsible for entering information accurately and for maintaining appropriate backups of information you wish to retain. PBH 1.0 primarily stores training information locally. Uninstalling PBH, clearing application data, device loss or device failure may remove locally stored information.</Section>
<Section title="6. Exports and third-party services">If you export data, share content or open an external resource, your use of the receiving app, website or service is subject to that provider's terms and policies. PBH is not responsible for third-party services outside its control.</Section>
<Section title="7. Intellectual property">PBH's original application design, branding, program content, text, graphics and other original material are protected by applicable intellectual-property laws. Third-party and open-source components remain subject to their respective licences. You may use PBH for personal lawful use, but may not copy, resell, misrepresent or redistribute protected PBH content except where applicable law or a third-party licence permits it.</Section>
<Section title="8. Availability and changes">PBH may be updated, corrected, changed or discontinued. Features can evolve as the training system and platform requirements change. Reasonable efforts are made to provide a reliable application, but uninterrupted or error-free operation is not guaranteed.</Section>
<Section title="9. Liability">To the extent permitted by applicable law, PBH and its developer are not liable for indirect or consequential losses arising from use of the application. Nothing in these Terms excludes or limits rights or liability that cannot legally be excluded, including mandatory consumer rights.</Section>
<Section title="10. Governing law">These Terms are governed by the laws of Portugal, without depriving consumers of mandatory protections that apply under the law of their country of residence.</Section>
<Section title="11. Changes and contact">These Terms may be updated when PBH or applicable requirements change. The current version displays its last-updated date. Questions can be sent to pbh.coach@gmail.com.</Section>
</ScrollView></SafeAreaView></>}
const createStyles=(palette: AppPalette)=>StyleSheet.create({screen:{flex:1,backgroundColor:palette.background},content:{padding:18,paddingBottom:44},back:{alignSelf:"flex-start",paddingVertical:6,marginBottom:8},backText:{color:palette.primary,fontWeight:"700",fontSize:15},title:{color:palette.text,fontSize:30,fontWeight:"800"},meta:{color:palette.textMuted,fontSize:13,lineHeight:19,marginTop:7,marginBottom:20},section:{backgroundColor:palette.surface,borderWidth:1,borderColor:palette.border,borderRadius:14,padding:15,marginBottom:10},heading:{color:palette.accent,fontSize:15,fontWeight:"800",marginBottom:7},onlineButton:{alignSelf:"flex-start",backgroundColor:palette.surfaceAlt,borderWidth:1,borderColor:palette.accent,borderRadius:10,paddingVertical:10,paddingHorizontal:13,marginBottom:18},onlineButtonText:{color:palette.accent,fontSize:14,fontWeight:"800"},body:{color:palette.textMuted,fontSize:14,lineHeight:21}});
